// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryVcsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVcsRequest) Reset()         { *m = QueryVcsRequest{} }
func (m *QueryVcsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVcsRequest) ProtoMessage()    {}
func (*QueryVcsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2abcd2561aaee, []int{0}
}
func (m *QueryVcsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVcsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVcsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVcsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVcsRequest.Merge(m, src)
}
func (m *QueryVcsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVcsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVcsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVcsRequest proto.InternalMessageInfo

func (m *QueryVcsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryVcsResponse struct {
	Vcs        []*VerifiableCredential `protobuf:"bytes,1,rep,name=vcs,proto3" json:"vcs,omitempty"`
	Pagination *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryVcsResponse) Reset()         { *m = QueryVcsResponse{} }
func (m *QueryVcsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVcsResponse) ProtoMessage()    {}
func (*QueryVcsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2abcd2561aaee, []int{1}
}
func (m *QueryVcsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVcsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVcsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVcsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVcsResponse.Merge(m, src)
}
func (m *QueryVcsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVcsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVcsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVcsResponse proto.InternalMessageInfo

func (m *QueryVcsResponse) GetVcs() []*VerifiableCredential {
	if m != nil {
		return m.Vcs
	}
	return nil
}

func (m *QueryVcsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryVcRequest struct {
	VcId string `protobuf:"bytes,1,opt,name=vcId,proto3" json:"vcId,omitempty"`
}

func (m *QueryVcRequest) Reset()         { *m = QueryVcRequest{} }
func (m *QueryVcRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVcRequest) ProtoMessage()    {}
func (*QueryVcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2abcd2561aaee, []int{2}
}
func (m *QueryVcRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVcRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVcRequest.Merge(m, src)
}
func (m *QueryVcRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVcRequest proto.InternalMessageInfo

func (m *QueryVcRequest) GetVcId() string {
	if m != nil {
		return m.VcId
	}
	return ""
}

type QueryVcResponse struct {
	Vc *VerifiableCredential `protobuf:"bytes,1,opt,name=vc,proto3" json:"vc,omitempty"`
}

func (m *QueryVcResponse) Reset()         { *m = QueryVcResponse{} }
func (m *QueryVcResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVcResponse) ProtoMessage()    {}
func (*QueryVcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2abcd2561aaee, []int{3}
}
func (m *QueryVcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVcResponse.Merge(m, src)
}
func (m *QueryVcResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVcResponse proto.InternalMessageInfo

func (m *QueryVcResponse) GetVc() *VerifiableCredential {
	if m != nil {
		return m.Vc
	}
	return nil
}

type QueryValidateVcRequest struct {
	VcId   string `protobuf:"bytes,1,opt,name=vcId,proto3" json:"vcId,omitempty"`
	PubKey string `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
}

func (m *QueryValidateVcRequest) Reset()         { *m = QueryValidateVcRequest{} }
func (m *QueryValidateVcRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidateVcRequest) ProtoMessage()    {}
func (*QueryValidateVcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2abcd2561aaee, []int{4}
}
func (m *QueryValidateVcRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidateVcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidateVcRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidateVcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidateVcRequest.Merge(m, src)
}
func (m *QueryValidateVcRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidateVcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidateVcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidateVcRequest proto.InternalMessageInfo

func (m *QueryValidateVcRequest) GetVcId() string {
	if m != nil {
		return m.VcId
	}
	return ""
}

func (m *QueryValidateVcRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type QueryValidateVcResponse struct {
	ValidationRes bool `protobuf:"varint,1,opt,name=validationRes,proto3" json:"validationRes,omitempty"`
}

func (m *QueryValidateVcResponse) Reset()         { *m = QueryValidateVcResponse{} }
func (m *QueryValidateVcResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidateVcResponse) ProtoMessage()    {}
func (*QueryValidateVcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77e2abcd2561aaee, []int{5}
}
func (m *QueryValidateVcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidateVcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidateVcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidateVcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidateVcResponse.Merge(m, src)
}
func (m *QueryValidateVcResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidateVcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidateVcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidateVcResponse proto.InternalMessageInfo

func (m *QueryValidateVcResponse) GetValidationRes() bool {
	if m != nil {
		return m.ValidationRes
	}
	return false
}

func init() {
	proto.RegisterType((*QueryVcsRequest)(nil), "stan14100.ngi.vc.QueryVcsRequest")
	proto.RegisterType((*QueryVcsResponse)(nil), "stan14100.ngi.vc.QueryVcsResponse")
	proto.RegisterType((*QueryVcRequest)(nil), "stan14100.ngi.vc.QueryVcRequest")
	proto.RegisterType((*QueryVcResponse)(nil), "stan14100.ngi.vc.QueryVcResponse")
	proto.RegisterType((*QueryValidateVcRequest)(nil), "stan14100.ngi.vc.QueryValidateVcRequest")
	proto.RegisterType((*QueryValidateVcResponse)(nil), "stan14100.ngi.vc.QueryValidateVcResponse")
}

func init() { proto.RegisterFile("vc/query.proto", fileDescriptor_77e2abcd2561aaee) }

var fileDescriptor_77e2abcd2561aaee = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0xb3, 0x1b, 0x2d, 0xf6, 0x15, 0x6b, 0x19, 0x34, 0x2d, 0x4b, 0x5c, 0xd2, 0xb5, 0x68,
	0xf5, 0xb0, 0xd3, 0x54, 0x11, 0x2f, 0x22, 0xa8, 0x58, 0x82, 0x20, 0xba, 0x87, 0x80, 0xde, 0x66,
	0x27, 0xe3, 0x3a, 0x98, 0xce, 0x6c, 0x33, 0x93, 0xc1, 0x5c, 0x05, 0xef, 0x82, 0xf8, 0x9d, 0x3c,
	0x16, 0xbc, 0x78, 0x94, 0x44, 0xbf, 0x87, 0x64, 0x66, 0x9a, 0x34, 0x69, 0x1b, 0x73, 0xdb, 0x9d,
	0xf9, 0xbf, 0xdf, 0xfb, 0xbd, 0xd9, 0x59, 0x58, 0x37, 0x14, 0x1f, 0xf5, 0x59, 0x6f, 0x90, 0x96,
	0x3d, 0xa9, 0x25, 0xda, 0x50, 0x9a, 0x88, 0xe6, 0x83, 0xe6, 0xde, 0x5e, 0x2a, 0x0a, 0x9e, 0x1a,
	0x1a, 0xad, 0x19, 0x8a, 0x0d, 0x75, 0xdb, 0x51, 0xbd, 0x90, 0xb2, 0xe8, 0x32, 0x4c, 0x4a, 0x8e,
	0x89, 0x10, 0x52, 0x13, 0xcd, 0xa5, 0x50, 0x7e, 0xf7, 0x1e, 0x95, 0xea, 0x50, 0x2a, 0x9c, 0x13,
	0xc5, 0x1c, 0x15, 0x9b, 0x66, 0xce, 0x34, 0x69, 0xe2, 0x92, 0x14, 0x5c, 0xd8, 0xb0, 0xcb, 0x26,
	0x6f, 0xe1, 0xda, 0x9b, 0x71, 0xa2, 0x4d, 0x55, 0xc6, 0x8e, 0xfa, 0x4c, 0x69, 0xf4, 0x02, 0x60,
	0x1a, 0xdb, 0x0a, 0x1a, 0xc1, 0xee, 0xda, 0xfe, 0xed, 0xd4, 0x31, 0xd3, 0x31, 0x33, 0x75, 0xa6,
	0x9e, 0x99, 0xbe, 0x26, 0x05, 0xf3, 0xb5, 0xd9, 0xa9, 0xca, 0xe4, 0x7b, 0x00, 0x1b, 0x53, 0xb6,
	0x2a, 0xa5, 0x50, 0x0c, 0x3d, 0x82, 0xaa, 0xa1, 0x6a, 0x2b, 0x68, 0x54, 0x2d, 0x75, 0x7e, 0xcc,
	0xb4, 0xcd, 0x7a, 0xfc, 0x3d, 0x27, 0x79, 0x97, 0x3d, 0xeb, 0xb1, 0x0e, 0x13, 0x9a, 0x93, 0x6e,
	0x36, 0x2e, 0x41, 0x07, 0x33, 0x5a, 0xa1, 0xd5, 0xba, 0xf3, 0x5f, 0x2d, 0xd7, 0x76, 0xc6, 0x6b,
	0x07, 0xd6, 0xbd, 0xd6, 0xc9, 0xc4, 0x08, 0x2e, 0x19, 0xda, 0xea, 0xd8, 0x59, 0x57, 0x33, 0xfb,
	0x9c, 0xb4, 0x26, 0x07, 0x33, 0x71, 0x7f, 0x08, 0xa1, 0xa1, 0x93, 0x03, 0x59, 0x4e, 0x3d, 0x34,
	0x34, 0x79, 0x0e, 0x35, 0x87, 0x22, 0x5d, 0xde, 0x21, 0x9a, 0x2d, 0x6c, 0x8c, 0x6a, 0xb0, 0x52,
	0xf6, 0xf3, 0x97, 0x6c, 0x60, 0x67, 0x5c, 0xcd, 0xfc, 0x5b, 0xf2, 0x04, 0x36, 0xcf, 0x50, 0xbc,
	0xd8, 0x0e, 0x5c, 0x35, 0x6e, 0x95, 0x4b, 0x91, 0x31, 0x65, 0x79, 0x57, 0xb2, 0xd9, 0xc5, 0xfd,
	0xbf, 0x21, 0x5c, 0xb6, 0x04, 0xf4, 0x11, 0xaa, 0x6d, 0xaa, 0xd0, 0xf6, 0xd9, 0x19, 0xe6, 0xee,
	0x42, 0x94, 0x2c, 0x8a, 0xb8, 0xee, 0xc9, 0xcd, 0xcf, 0x3f, 0xff, 0x7c, 0x0b, 0x37, 0xd1, 0x0d,
	0x3c, 0xc9, 0x62, 0x51, 0x70, 0x6c, 0x2f, 0xac, 0x42, 0x05, 0x84, 0x6d, 0x8a, 0x1a, 0x17, 0x82,
	0x4e, 0x5a, 0x6d, 0x2f, 0x48, 0xf8, 0x4e, 0x75, 0xdb, 0xa9, 0x86, 0xae, 0x9f, 0xd7, 0x09, 0x7d,
	0x09, 0x00, 0xa6, 0x87, 0x83, 0x76, 0x2f, 0xe2, 0xcd, 0x7f, 0x85, 0xe8, 0xee, 0x12, 0x49, 0x6f,
	0x90, 0x58, 0x83, 0x7a, 0x12, 0x9d, 0x63, 0xe0, 0xd3, 0x4f, 0x1f, 0xff, 0x18, 0xc6, 0xc1, 0xf1,
	0x30, 0x0e, 0x7e, 0x0f, 0xe3, 0xe0, 0xeb, 0x28, 0xae, 0x1c, 0x8f, 0xe2, 0xca, 0xaf, 0x51, 0x5c,
	0x79, 0x77, 0xab, 0xe0, 0xfa, 0x43, 0x3f, 0x4f, 0xa9, 0x3c, 0x3c, 0x55, 0xff, 0xea, 0xa0, 0x85,
	0x3f, 0x8d, 0x09, 0x7a, 0x50, 0x32, 0x95, 0xaf, 0xd8, 0x1f, 0xf3, 0xfe, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x68, 0x50, 0xc0, 0xfe, 0x13, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of vcs items.
	Vcs(ctx context.Context, in *QueryVcsRequest, opts ...grpc.CallOption) (*QueryVcsResponse, error)
	// Queries a list of vc items.
	Vc(ctx context.Context, in *QueryVcRequest, opts ...grpc.CallOption) (*QueryVcResponse, error)
	ValidateVc(ctx context.Context, in *QueryValidateVcRequest, opts ...grpc.CallOption) (*QueryValidateVcResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Vcs(ctx context.Context, in *QueryVcsRequest, opts ...grpc.CallOption) (*QueryVcsResponse, error) {
	out := new(QueryVcsResponse)
	err := c.cc.Invoke(ctx, "/stan14100.ngi.vc.Query/Vcs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Vc(ctx context.Context, in *QueryVcRequest, opts ...grpc.CallOption) (*QueryVcResponse, error) {
	out := new(QueryVcResponse)
	err := c.cc.Invoke(ctx, "/stan14100.ngi.vc.Query/Vc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidateVc(ctx context.Context, in *QueryValidateVcRequest, opts ...grpc.CallOption) (*QueryValidateVcResponse, error) {
	out := new(QueryValidateVcResponse)
	err := c.cc.Invoke(ctx, "/stan14100.ngi.vc.Query/ValidateVc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of vcs items.
	Vcs(context.Context, *QueryVcsRequest) (*QueryVcsResponse, error)
	// Queries a list of vc items.
	Vc(context.Context, *QueryVcRequest) (*QueryVcResponse, error)
	ValidateVc(context.Context, *QueryValidateVcRequest) (*QueryValidateVcResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Vcs(ctx context.Context, req *QueryVcsRequest) (*QueryVcsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vcs not implemented")
}
func (*UnimplementedQueryServer) Vc(ctx context.Context, req *QueryVcRequest) (*QueryVcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vc not implemented")
}
func (*UnimplementedQueryServer) ValidateVc(ctx context.Context, req *QueryValidateVcRequest) (*QueryValidateVcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateVc not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Vcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVcsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Vcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stan14100.ngi.vc.Query/Vcs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Vcs(ctx, req.(*QueryVcsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Vc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Vc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stan14100.ngi.vc.Query/Vc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Vc(ctx, req.(*QueryVcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidateVc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidateVcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidateVc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stan14100.ngi.vc.Query/ValidateVc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidateVc(ctx, req.(*QueryValidateVcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stan14100.ngi.vc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vcs",
			Handler:    _Query_Vcs_Handler,
		},
		{
			MethodName: "Vc",
			Handler:    _Query_Vc_Handler,
		},
		{
			MethodName: "ValidateVc",
			Handler:    _Query_ValidateVc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vc/query.proto",
}

func (m *QueryVcsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVcsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVcsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVcsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVcsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVcsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vcs) > 0 {
		for iNdEx := len(m.Vcs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vcs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryVcRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVcRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVcRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VcId) > 0 {
		i -= len(m.VcId)
		copy(dAtA[i:], m.VcId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VcId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Vc != nil {
		{
			size, err := m.Vc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidateVcRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidateVcRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidateVcRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.VcId) > 0 {
		i -= len(m.VcId)
		copy(dAtA[i:], m.VcId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VcId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidateVcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidateVcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidateVcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidationRes {
		i--
		if m.ValidationRes {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryVcsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVcsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Vcs) > 0 {
		for _, e := range m.Vcs {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVcRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VcId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vc != nil {
		l = m.Vc.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidateVcRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VcId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidateVcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValidationRes {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryVcsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVcsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVcsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVcsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVcsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVcsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vcs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vcs = append(m.Vcs, &VerifiableCredential{})
			if err := m.Vcs[len(m.Vcs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVcRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVcRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVcRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VcId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VcId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vc == nil {
				m.Vc = &VerifiableCredential{}
			}
			if err := m.Vc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidateVcRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidateVcRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidateVcRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VcId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VcId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidateVcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidateVcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidateVcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidationRes", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ValidationRes = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
